global using static ReactWithDotNet.WebSite.Showcases.Extensions;

namespace ReactWithDotNet.WebSite.Showcases;

record CountryType
{
    public string code { get; init; }
    public string label { get; init; }
    public string phone { get; init; }
    public bool suggested { get; set; }

}

static class Extensions
{
    
    // From https://bitbucket.org/atlassian/atlaskit-mk-2/raw/4ad0e56649c3e6c973e226b7efaeb28cb240ccb0/packages/core/select/src/data/countries.js
public  static  IReadOnlyList<CountryType> Countries = [
  new(){ code = "AD", label = "Andorra", phone =  "376" },
  new(){
    code = "AE",
    label = "United Arab Emirates",
    phone =  "971",
  },
  new(){ code = "AF", label = "Afghanistan", phone =  "93" },
  new(){
    code = "AG",
    label = "Antigua and Barbuda",
    phone =  "1-268",
  },
  new(){ code = "AI", label = "Anguilla", phone =  "1-264" },
  new(){ code = "AL", label = "Albania", phone =  "355" },
  new(){ code = "AM", label = "Armenia", phone =  "374" },
  new(){ code = "AO", label = "Angola", phone =  "244" },
  new(){ code = "AQ", label = "Antarctica", phone =  "672" },
  new(){ code = "AR", label = "Argentina", phone =  "54" },
  new(){ code = "AS", label = "American Samoa", phone =  "1-684" },
  new(){ code = "AT", label = "Austria", phone =  "43" },
  new(){
    code = "AU",
    label = "Australia",
    phone =  "61",
    suggested =  true,
  },
  new(){ code = "AW", label = "Aruba", phone =  "297" },
  new(){ code = "AX", label = "Alland Islands", phone =  "358" },
  new(){ code = "AZ", label = "Azerbaijan", phone =  "994" },
  new(){
    code = "BA",
    label = "Bosnia and Herzegovina",
    phone =  "387",
  },
  new(){ code = "BB", label = "Barbados", phone =  "1-246" },
  new(){ code = "BD", label = "Bangladesh", phone =  "880" },
  new(){ code = "BE", label = "Belgium", phone =  "32" },
  new(){ code = "BF", label = "Burkina Faso", phone =  "226" },
  new(){ code = "BG", label = "Bulgaria", phone =  "359" },
  new(){ code = "BH", label = "Bahrain", phone =  "973" },
  new(){ code = "BI", label = "Burundi", phone =  "257" },
  new(){ code = "BJ", label = "Benin", phone =  "229" },
  new(){ code = "BL", label = "Saint Barthelemy", phone =  "590" },
  new(){ code = "BM", label = "Bermuda", phone =  "1-441" },
  new(){ code = "BN", label = "Brunei Darussalam", phone =  "673" },
  new(){ code = "BO", label = "Bolivia", phone =  "591" },
  new(){ code = "BR", label = "Brazil", phone =  "55" },
  new(){ code = "BS", label = "Bahamas", phone =  "1-242" },
  new(){ code = "BT", label = "Bhutan", phone =  "975" },
  new(){ code = "BV", label = "Bouvet Island", phone =  "47" },
  new(){ code = "BW", label = "Botswana", phone =  "267" },
  new(){ code = "BY", label = "Belarus", phone =  "375" },
  new(){ code = "BZ", label = "Belize", phone =  "501" },
  new(){
    code = "CA",
    label = "Canada",
    phone =  "1",
    suggested =  true,
  },
  new(){
    code = "CC",
    label = "Cocos (Keeling) Islands",
    phone =  "61",
  },
  new(){
    code = "CD",
    label = "Congo, Democratic Republic of the",
    phone =  "243",
  },
  new(){
    code = "CF",
    label = "Central African Republic",
    phone =  "236",
  },
  new(){
    code = "CG",
    label = "Congo, Republic of the",
    phone =  "242",
  },
  new(){ code = "CH", label = "Switzerland", phone =  "41" },
  new(){ code = "CI", label = "Cote d\"Ivoire", phone =  "225" },
  new(){ code = "CK", label = "Cook Islands", phone =  "682" },
  new(){ code = "CL", label = "Chile", phone =  "56" },
  new(){ code = "CM", label = "Cameroon", phone =  "237" },
  new(){ code = "CN", label = "China", phone =  "86" },
  new(){ code = "CO", label = "Colombia", phone =  "57" },
  new(){ code = "CR", label = "Costa Rica", phone =  "506" },
  new(){ code = "CU", label = "Cuba", phone =  "53" },
  new(){ code = "CV", label = "Cape Verde", phone =  "238" },
  new(){ code = "CW", label = "Curacao", phone =  "599" },
  new(){ code = "CX", label = "Christmas Island", phone =  "61" },
  new(){ code = "CY", label = "Cyprus", phone =  "357" },
  new(){ code = "CZ", label = "Czech Republic", phone =  "420" },
  new(){
    code = "DE",
    label = "Germany",
    phone =  "49",
    suggested =  true,
  },
  new(){ code = "DJ", label = "Djibouti", phone =  "253" },
  new(){ code = "DK", label = "Denmark", phone =  "45" },
  new(){ code = "DM", label = "Dominica", phone =  "1-767" },
  new(){
    code = "DO",
    label = "Dominican Republic",
    phone =  "1-809",
  },
  new(){ code = "DZ", label = "Algeria", phone =  "213" },
  new(){ code = "EC", label = "Ecuador", phone =  "593" },
  new(){ code = "EE", label = "Estonia", phone =  "372" },
  new(){ code = "EG", label = "Egypt", phone =  "20" },
  new(){ code = "EH", label = "Western Sahara", phone =  "212" },
  new(){ code = "ER", label = "Eritrea", phone =  "291" },
  new(){ code = "ES", label = "Spain", phone =  "34" },
  new(){ code = "ET", label = "Ethiopia", phone =  "251" },
  new(){ code = "FI", label = "Finland", phone =  "358" },
  new(){ code = "FJ", label = "Fiji", phone =  "679" },
  new(){
    code = "FK",
    label = "Falkland Islands (Malvinas)",
    phone =  "500",
  },
  new(){
    code = "FM",
    label = "Micronesia, Federated States of",
    phone =  "691",
  },
  new(){ code = "FO", label = "Faroe Islands", phone =  "298" },
  new(){
    code = "FR",
    label = "France",
    phone =  "33",
    suggested =  true,
  },
  new(){ code = "GA", label = "Gabon", phone =  "241" },
  new(){ code = "GB", label = "United Kingdom", phone =  "44" },
  new(){ code = "GD", label = "Grenada", phone =  "1-473" },
  new(){ code = "GE", label = "Georgia", phone =  "995" },
  new(){ code = "GF", label = "French Guiana", phone =  "594" },
  new(){ code = "GG", label = "Guernsey", phone =  "44" },
  new(){ code = "GH", label = "Ghana", phone =  "233" },
  new(){ code = "GI", label = "Gibraltar", phone =  "350" },
  new(){ code = "GL", label = "Greenland", phone =  "299" },
  new(){ code = "GM", label = "Gambia", phone =  "220" },
  new(){ code = "GN", label = "Guinea", phone =  "224" },
  new(){ code = "GP", label = "Guadeloupe", phone =  "590" },
  new(){ code = "GQ", label = "Equatorial Guinea", phone =  "240" },
  new(){ code = "GR", label = "Greece", phone =  "30" },
  new(){
    code = "GS",
    label = "South Georgia and the South Sandwich Islands",
    phone =  "500",
  },
  new(){ code = "GT", label = "Guatemala", phone =  "502" },
  new(){ code = "GU", label = "Guam", phone =  "1-671" },
  new(){ code = "GW", label = "Guinea-Bissau", phone =  "245" },
  new(){ code = "GY", label = "Guyana", phone =  "592" },
  new(){ code = "HK", label = "Hong Kong", phone =  "852" },
  new(){
    code = "HM",
    label = "Heard Island and McDonald Islands",
    phone =  "672",
  },
  new(){ code = "HN", label = "Honduras", phone =  "504" },
  new(){ code = "HR", label = "Croatia", phone =  "385" },
  new(){ code = "HT", label = "Haiti", phone =  "509" },
  new(){ code = "HU", label = "Hungary", phone =  "36" },
  new(){ code = "ID", label = "Indonesia", phone =  "62" },
  new(){ code = "IE", label = "Ireland", phone =  "353" },
  new(){ code = "IL", label = "Israel", phone =  "972" },
  new(){ code = "IM", label = "Isle of Man", phone =  "44" },
  new(){ code = "IN", label = "India", phone =  "91" },
  new(){
    code = "IO",
    label = "British Indian Ocean Territory",
    phone =  "246",
  },
  new(){ code = "IQ", label = "Iraq", phone =  "964" },
  new(){
    code = "IR",
    label = "Iran, Islamic Republic of",
    phone =  "98",
  },
  new(){ code = "IS", label = "Iceland", phone =  "354" },
  new(){ code = "IT", label = "Italy", phone =  "39" },
  new(){ code = "JE", label = "Jersey", phone =  "44" },
  new(){ code = "JM", label = "Jamaica", phone =  "1-876" },
  new(){ code = "JO", label = "Jordan", phone =  "962" },
  new(){
    code = "JP",
    label = "Japan",
    phone =  "81",
    suggested =  true,
  },
  new(){ code = "KE", label = "Kenya", phone =  "254" },
  new(){ code = "KG", label = "Kyrgyzstan", phone =  "996" },
  new(){ code = "KH", label = "Cambodia", phone =  "855" },
  new(){ code = "KI", label = "Kiribati", phone =  "686" },
  new(){ code = "KM", label = "Comoros", phone =  "269" },
  new(){
    code = "KN",
    label = "Saint Kitts and Nevis",
    phone =  "1-869",
  },
  new(){
    code = "KP",
    label = "Korea, Democratic People\"s Republic of",
    phone =  "850",
  },
  new(){ code = "KR", label = "Korea, Republic of", phone =  "82" },
  new(){ code = "KW", label = "Kuwait", phone =  "965" },
  new(){ code = "KY", label = "Cayman Islands", phone =  "1-345" },
  new(){ code = "KZ", label = "Kazakhstan", phone =  "7" },
  new(){
    code = "LA",
    label = "Lao People\"s Democratic Republic",
    phone =  "856",
  },
  new(){ code = "LB", label = "Lebanon", phone =  "961" },
  new(){ code = "LC", label = "Saint Lucia", phone =  "1-758" },
  new(){ code = "LI", label = "Liechtenstein", phone =  "423" },
  new(){ code = "LK", label = "Sri Lanka", phone =  "94" },
  new(){ code = "LR", label = "Liberia", phone =  "231" },
  new(){ code = "LS", label = "Lesotho", phone =  "266" },
  new(){ code = "LT", label = "Lithuania", phone =  "370" },
  new(){ code = "LU", label = "Luxembourg", phone =  "352" },
  new(){ code = "LV", label = "Latvia", phone =  "371" },
  new(){ code = "LY", label = "Libya", phone =  "218" },
  new(){ code = "MA", label = "Morocco", phone =  "212" },
  new(){ code = "MC", label = "Monaco", phone =  "377" },
  new(){
    code = "MD",
    label = "Moldova, Republic of",
    phone =  "373",
  },
  new(){ code = "ME", label = "Montenegro", phone =  "382" },
  new(){
    code = "MF",
    label = "Saint Martin (French part)",
    phone =  "590",
  },
  new(){ code = "MG", label = "Madagascar", phone =  "261" },
  new(){ code = "MH", label = "Marshall Islands", phone =  "692" },
  new(){
    code = "MK",
    label = "Macedonia, the Former Yugoslav Republic of",
    phone =  "389",
  },
  new(){ code = "ML", label = "Mali", phone =  "223" },
  new(){ code = "MM", label = "Myanmar", phone =  "95" },
  new(){ code = "MN", label = "Mongolia", phone =  "976" },
  new(){ code = "MO", label = "Macao", phone =  "853" },
  new(){
    code = "MP",
    label = "Northern Mariana Islands",
    phone =  "1-670",
  },
  new(){ code = "MQ", label = "Martinique", phone =  "596" },
  new(){ code = "MR", label = "Mauritania", phone =  "222" },
  new(){ code = "MS", label = "Montserrat", phone =  "1-664" },
  new(){ code = "MT", label = "Malta", phone =  "356" },
  new(){ code = "MU", label = "Mauritius", phone =  "230" },
  new(){ code = "MV", label = "Maldives", phone =  "960" },
  new(){ code = "MW", label = "Malawi", phone =  "265" },
  new(){ code = "MX", label = "Mexico", phone =  "52" },
  new(){ code = "MY", label = "Malaysia", phone =  "60" },
  new(){ code = "MZ", label = "Mozambique", phone =  "258" },
  new(){ code = "NA", label = "Namibia", phone =  "264" },
  new(){ code = "NC", label = "New Caledonia", phone =  "687" },
  new(){ code = "NE", label = "Niger", phone =  "227" },
  new(){ code = "NF", label = "Norfolk Island", phone =  "672" },
  new(){ code = "NG", label = "Nigeria", phone =  "234" },
  new(){ code = "NI", label = "Nicaragua", phone =  "505" },
  new(){ code = "NL", label = "Netherlands", phone =  "31" },
  new(){ code = "NO", label = "Norway", phone =  "47" },
  new(){ code = "NP", label = "Nepal", phone =  "977" },
  new(){ code = "NR", label = "Nauru", phone =  "674" },
  new(){ code = "NU", label = "Niue", phone =  "683" },
  new(){ code = "NZ", label = "New Zealand", phone =  "64" },
  new(){ code = "OM", label = "Oman", phone =  "968" },
  new(){ code = "PA", label = "Panama", phone =  "507" },
  new(){ code = "PE", label = "Peru", phone =  "51" },
  new(){ code = "PF", label = "French Polynesia", phone =  "689" },
  new(){ code = "PG", label = "Papua New Guinea", phone =  "675" },
  new(){ code = "PH", label = "Philippines", phone =  "63" },
  new(){ code = "PK", label = "Pakistan", phone =  "92" },
  new(){ code = "PL", label = "Poland", phone =  "48" },
  new(){
    code = "PM",
    label = "Saint Pierre and Miquelon",
    phone =  "508",
  },
  new(){ code = "PN", label = "Pitcairn", phone =  "870" },
  new(){ code = "PR", label = "Puerto Rico", phone =  "1" },
  new(){
    code = "PS",
    label = "Palestine, State of",
    phone =  "970",
  },
  new(){ code = "PT", label = "Portugal", phone =  "351" },
  new(){ code = "PW", label = "Palau", phone =  "680" },
  new(){ code = "PY", label = "Paraguay", phone =  "595" },
  new(){ code = "QA", label = "Qatar", phone =  "974" },
  new(){ code = "RE", label = "Reunion", phone =  "262" },
  new(){ code = "RO", label = "Romania", phone =  "40" },
  new(){ code = "RS", label = "Serbia", phone =  "381" },
  new(){ code = "RU", label = "Russian Federation", phone =  "7" },
  new(){ code = "RW", label = "Rwanda", phone =  "250" },
  new(){ code = "SA", label = "Saudi Arabia", phone =  "966" },
  new(){ code = "SB", label = "Solomon Islands", phone =  "677" },
  new(){ code = "SC", label = "Seychelles", phone =  "248" },
  new(){ code = "SD", label = "Sudan", phone =  "249" },
  new(){ code = "SE", label = "Sweden", phone =  "46" },
  new(){ code = "SG", label = "Singapore", phone =  "65" },
  new(){ code = "SH", label = "Saint Helena", phone =  "290" },
  new(){ code = "SI", label = "Slovenia", phone =  "386" },
  new(){
    code = "SJ",
    label = "Svalbard and Jan Mayen",
    phone =  "47",
  },
  new(){ code = "SK", label = "Slovakia", phone =  "421" },
  new(){ code = "SL", label = "Sierra Leone", phone =  "232" },
  new(){ code = "SM", label = "San Marino", phone =  "378" },
  new(){ code = "SN", label = "Senegal", phone =  "221" },
  new(){ code = "SO", label = "Somalia", phone =  "252" },
  new(){ code = "SR", label = "Suriname", phone =  "597" },
  new(){ code = "SS", label = "South Sudan", phone =  "211" },
  new(){
    code = "ST",
    label = "Sao Tome and Principe",
    phone =  "239",
  },
  new(){ code = "SV", label = "El Salvador", phone =  "503" },
  new(){
    code = "SX",
    label = "Sint Maarten (Dutch part)",
    phone =  "1-721",
  },
  new(){
    code = "SY",
    label = "Syrian Arab Republic",
    phone =  "963",
  },
  new(){ code = "SZ", label = "Swaziland", phone =  "268" },
  new(){
    code = "TC",
    label = "Turks and Caicos Islands",
    phone =  "1-649",
  },
  new(){ code = "TD", label = "Chad", phone =  "235" },
  new(){
    code = "TF",
    label = "French Southern Territories",
    phone =  "262",
  },
  new(){ code = "TG", label = "Togo", phone =  "228" },
  new(){ code = "TH", label = "Thailand", phone =  "66" },
  new(){ code = "TJ", label = "Tajikistan", phone =  "992" },
  new(){ code = "TK", label = "Tokelau", phone =  "690" },
  new(){ code = "TL", label = "Timor-Leste", phone =  "670" },
  new(){ code = "TM", label = "Turkmenistan", phone =  "993" },
  new(){ code = "TN", label = "Tunisia", phone =  "216" },
  new(){ code = "TO", label = "Tonga", phone =  "676" },
  new(){ code = "TR", label = "Turkey", phone =  "90" },
  new(){
    code = "TT",
    label = "Trinidad and Tobago",
    phone =  "1-868",
  },
  new(){ code = "TV", label = "Tuvalu", phone =  "688" },
  new(){
    code = "TW",
    label = "Taiwan",
    phone =  "886",
  },
  new(){
    code = "TZ",
    label = "United Republic of Tanzania",
    phone =  "255",
  },
  new(){ code = "UA", label = "Ukraine", phone =  "380" },
  new(){ code = "UG", label = "Uganda", phone =  "256" },
  new(){
    code = "US",
    label = "United States",
    phone =  "1",
    suggested =  true,
  },
  new(){ code = "UY", label = "Uruguay", phone =  "598" },
  new(){ code = "UZ", label = "Uzbekistan", phone =  "998" },
  new(){
    code = "VA",
    label = "Holy See (Vatican City State)",
    phone =  "379",
  },
  new(){
    code = "VC",
    label = "Saint Vincent and the Grenadines",
    phone =  "1-784",
  },
  new(){ code = "VE", label = "Venezuela", phone =  "58" },
  new(){
    code = "VG",
    label = "British Virgin Islands",
    phone =  "1-284",
  },
  new(){
    code = "VI",
    label = "US Virgin Islands",
    phone =  "1-340",
  },
  new(){ code = "VN", label = "Vietnam", phone =  "84" },
  new(){ code = "VU", label = "Vanuatu", phone =  "678" },
  new(){ code = "WF", label = "Wallis and Futuna", phone =  "681" },
  new(){ code = "WS", label = "Samoa", phone =  "685" },
  new(){ code = "XK", label = "Kosovo", phone =  "383" },
  new(){ code = "YE", label = "Yemen", phone =  "967" },
  new(){ code = "YT", label = "Mayotte", phone =  "262" },
  new(){ code = "ZA", label = "South Africa", phone =  "27" },
  new(){ code = "ZM", label = "Zambia", phone =  "260" },
  new(){ code = "ZW", label = "Zimbabwe", phone =  "263" },
];
}